# Generated by Django 5.1.2 on 2024-11-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_compra_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor'),
            preserve_default=False,
        ),
    ]
