# Generated by Django 5.1.2 on 2024-11-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_compra_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
